<#
.SYNOPSIS
    Build a Windows release of Uncensored Local AI and package it as an installer.

.DESCRIPTION
    Runs `flutter build windows --release`, then produces:
      * dist\UncensoredLocalAI-<version>-windows-x64-setup.exe  (needs Inno Setup)
      * dist\UncensoredLocalAI-<version>-windows-x64-portable.zip (always)

    The portable zip is the fallback when Inno Setup is not installed, and is
    also what USB / no-install users want.

.PARAMETER SkipBuild
    Package whatever is already in build\windows\x64\runner\Release.

.PARAMETER PortableOnly
    Skip the installer and produce only the portable zip.

.EXAMPLE
    .\packaging\windows\build-installer.ps1

.NOTES
    Inno Setup 6: https://jrsoftware.org/isdl.php  (or: winget install JRSoftware.InnoSetup)
#>

[CmdletBinding()]
param(
    [switch]$SkipBuild,
    [switch]$PortableOnly
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..')
Set-Location $RepoRoot

$AppName    = 'UncensoredLocalAI'
$DisplayName = 'Uncensored Local AI'
$Publisher  = 'Uncensored Local AI Contributors'
$BinaryName = 'portable_ai_flutter.exe'
$ReleaseDir = 'build\windows\x64\runner\Release'
$DistDir    = 'dist'

function Write-Step($Message) { Write-Host "==> $Message" -ForegroundColor Cyan }
function Write-Fail($Message) { Write-Host "Error: $Message" -ForegroundColor Red; exit 1 }

# ── Version ─────────────────────────────────────────────────────────────
$versionLine = Select-String -Path 'pubspec.yaml' -Pattern '^version:' | Select-Object -First 1
if (-not $versionLine) { Write-Fail 'Could not read version from pubspec.yaml.' }
$Version = ($versionLine.Line -replace '^version:\s*', '') -split '\+' | Select-Object -First 1
$Version = $Version.Trim()
Write-Step "Packaging $DisplayName $Version"

# ── Build ───────────────────────────────────────────────────────────────
if (-not $SkipBuild) {
    Write-Step 'Building release bundle'
    & flutter build windows --release
    if ($LASTEXITCODE -ne 0) { Write-Fail 'flutter build windows failed.' }
}

$exePath = Join-Path $ReleaseDir $BinaryName
if (-not (Test-Path $exePath)) {
    Write-Fail "Expected $exePath. Run without -SkipBuild first."
}

New-Item -ItemType Directory -Force -Path $DistDir | Out-Null

# ── Portable zip ────────────────────────────────────────────────────────
Write-Step 'Creating portable zip'
$zipPath = Join-Path $DistDir "$AppName-$Version-windows-x64-portable.zip"
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Compress-Archive -Path (Join-Path $ReleaseDir '*') -DestinationPath $zipPath
Write-Host "    $zipPath"

if ($PortableOnly) {
    Write-Step 'Done (portable only).'
    exit 0
}

# ── Locate Inno Setup ───────────────────────────────────────────────────
$iscc = $null
foreach ($candidate in @(
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles}\Inno Setup 6\ISCC.exe"
)) {
    if ($candidate -and (Test-Path $candidate)) { $iscc = $candidate; break }
}
if (-not $iscc) {
    $cmd = Get-Command ISCC.exe -ErrorAction SilentlyContinue
    if ($cmd) { $iscc = $cmd.Source }
}

if (-not $iscc) {
    Write-Host ''
    Write-Host 'Inno Setup was not found, so no installer was produced.' -ForegroundColor Yellow
    Write-Host 'Install it with:  winget install JRSoftware.InnoSetup' -ForegroundColor Yellow
    Write-Host "The portable zip is ready at $zipPath" -ForegroundColor Yellow
    exit 0
}

# ── Generate the Inno Setup script ──────────────────────────────────────
Write-Step 'Generating installer script'
$issPath = Join-Path $DistDir "$AppName.iss"
$sourceDir = (Resolve-Path $ReleaseDir).Path
$outDir = (Resolve-Path $DistDir).Path

$iconLine = ''
$iconCandidate = Join-Path $RepoRoot 'windows\runner\resources\app_icon.ico'
if (Test-Path $iconCandidate) {
    $iconLine = "SetupIconFile=$iconCandidate"
}

$iss = @"
; Generated by packaging/windows/build-installer.ps1 — do not edit by hand.
#define MyAppName "$DisplayName"
#define MyAppVersion "$Version"
#define MyAppPublisher "$Publisher"
#define MyAppExeName "$BinaryName"

[Setup]
AppId={{8F3C1A47-5D2E-4B9A-9C31-7A6E5B4D2F10}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppSupportURL=https://github.com/techjarves/Uncensored-Local-AI-Multiplatform
DefaultDirName={autopf}\$AppName
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=$outDir
OutputBaseFilename=$AppName-$Version-windows-x64-setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequiredOverridesAllowed=dialog
UninstallDisplayName={#MyAppName}
$iconLine

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional shortcuts:"

[Files]
Source: "$sourceDir\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent

; Downloaded GGUF models live in the user profile, not under {app} — leave
; them in place so an uninstall never deletes multi-GB downloads silently.
[UninstallDelete]
Type: filesandordirs; Name: "{app}\data"
"@

Set-Content -Path $issPath -Value $iss -Encoding UTF8

# ── Compile ─────────────────────────────────────────────────────────────
Write-Step 'Compiling installer'
& $iscc $issPath
if ($LASTEXITCODE -ne 0) { Write-Fail 'ISCC failed to compile the installer.' }

$setupPath = Join-Path $DistDir "$AppName-$Version-windows-x64-setup.exe"
Write-Step 'Done'
Write-Host "    $setupPath"
Write-Host "    $zipPath"
Write-Host ''
Write-Host 'Note: the installer is unsigned, so SmartScreen will warn on first run.' -ForegroundColor Yellow
Write-Host 'See packaging/README.md for code-signing notes.' -ForegroundColor Yellow
